name: CI
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Enable Corepack and Install Dependencies
        run: |
          nvm use 20 && node --version
          corepack enable && npx --yes pnpm install
      - name: Install Dependencies
        run: pnpm install
      - name: Lint and Generate
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: |
          pnpm lint
          pnpm generate
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
